#!/bin/sh

# Copyright (c) 2014, Victor Arribas Raigadas
# All rights reserved.
#
# This software is under BSD 3-Clause License.
# You could get a copy at http://opensource.org/licenses/BSD-3-Clause

if [ -d $HOME/.vnc ]; then
	cd $HOME/.vnc
else
	echo "$HOME/.vnc not found" >&2
	exit 1
fi

FILES=$(ls -1 | grep "\.pid")

if [ $(echo $FILES | wc -w) -eq 0 ]; then
	echo "There are not vnc sessions running currently"
else
	for i in $FILES; do
		echo " $i"
	done
fi
